# Generated by Django 3.2.4 on 2021-07-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ac', models.IntegerField(default='')),
                ('cctv', models.IntegerField(default='')),
                ('fire_alarm', models.IntegerField(default='')),
                ('inverters', models.IntegerField(default='')),
                ('counting_machine', models.IntegerField(default='')),
                ('tv', models.IntegerField(default='')),
            ],
        ),
    ]
