# Generated by Django 3.2.4 on 2021-07-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ac',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(default='', max_length=100)),
                ('model', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default='')),
                ('available', models.IntegerField(default='')),
                ('sold', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='cctv',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(default='', max_length=100)),
                ('model', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default='')),
                ('available', models.IntegerField(default='')),
                ('sold', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='counting_machine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(default='', max_length=100)),
                ('model', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default='')),
                ('available', models.IntegerField(default='')),
                ('sold', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='fire_alarm',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(default='', max_length=100)),
                ('model', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default='')),
                ('available', models.IntegerField(default='')),
                ('sold', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='inverters',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(default='', max_length=100)),
                ('model', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default='')),
                ('available', models.IntegerField(default='')),
                ('sold', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='tv',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(default='', max_length=100)),
                ('model', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default='')),
                ('available', models.IntegerField(default='')),
                ('sold', models.IntegerField(default='')),
            ],
        ),
    ]
